@startuml

interface Factory {
    +create()
}
interface Product {
    +playAudio()
}
class ConcreteFactory
class ConcreteProduct

Product <|-- ConcreteProduct
Factory <|-- ConcreteFactory

Factory ..> Product
ConcreteFactory ..> ConcreteProduct

note right of Factory: [意图]\n定义一个用于创建对象的接口，让子类决定实例化哪个类。\n工厂方式模式使一个类的实例化延迟到其子类。
@enduml
